# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js server to Azure Web App - tichsy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm install
        
      - name: Build server
        run: npx turbo run build --filter=server
        
      - name: Prepare deploy package
        run: |
          mkdir deploy
          cp -r apps/server/dist deploy/dist
          cp apps/server/package.json deploy/package.json

      - name: Generate deploy lockfile
        working-directory: deploy
        run: npm install --package-lock-only
          
      - name: Install production dependencies
        working-directory: deploy
        run: npm ci --omit=dev
        
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: deploy

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_4EA662C107674E878CC8CAB2C3918642 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_FB243BAD09954E2F93C957AEF6F81070 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_6E03214276C548F4B796F077FC17FBA0 }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'tichsy'
          slot-name: 'Production'
          package: .
          